### PR TITLE
Fixing memory leaks in Cell struct 

### PR DESCRIPTION
**Pull request by AniketKumar2500**

### CODE REVIEW

**Review by gekkowrld — CHANGES_REQUESTED** [review]
An Error encountered when running csq

As seen above, there is an error when compiling the code, there is an extra "Csq" hard coded in that causes the issue, can you look into it

**Comment by AniketKumar2500** [comment]
Well i did it because in my system it was required in order to get Csq path but its different in yours so i think we should remake the system to identify paths.

**Comment by gekkowrld** [comment]
Can you try cloning the repo in a fresh environment, it seems that your local setup can be the problem.

**Comment by AniketKumar2500** [comment]
I did that but it didn't work...

**Comment by gekkowrld** [comment]
I'll be rewriting the bash script to reflect changes in the python file, should fix installation. That will require that you edit your `.bashrc` file before testing.

**Pull request closed without merging**
