### PR TITLE
Make csq accesible everywhere

### PR DESCRIPTION
**Pull request by gekkowrld**
@AniketKumar2500 can you check it out

### CODE REVIEW

**Comment by AniketKumar2500** [comment]
I tried to eval all your changes in codespace and see this is the result it doesn't work as expected.

Screenshot_20230821_172137

**Comment by WithSJ** [comment]
I'm facing some issues while building and running the csq. During the build process, I encountered the following error message:

```
cp: cannot stat 'AST/'$'\n''Builtin/'$'\n''Grammar/'$'\n''Parser/'$'\n''Runtime/'$'\n''Tokenizer/': No such file or directory
```
the csq build ultimately succeeded. However, when I attempt to run my program using the command csq hello in the terminal, I encounter a different error:

*hello.csq is my code file it have print("Hello World")

```
hello.cpp:1:10: fatal error: /home/withsj/.local/include/csq/Builtin/basic.h: No such file or directory
    1 | #include "/home/withsj/.local/include/csq/Builtin/basic.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

It seems that the required file or directory structure is not correctly set up, leading to these errors.

**Comment by AniketKumar2500** [comment]
Ok

**Comment by WithSJ** [comment]
I encountered the following error while compiling my code:

```
hello.cpp:1:10: fatal error: /home/withsj/.local/include/csq/Builtin/basic.h: No such file or directory
    1 | #include "/home/withsj/.local/include/csq/Builtin/basic.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

Upon investigating, I realized that the required include directory was missing in my .local folder, leading to this error. To address this, I followed the steps outlined below.

**Solution Steps:**

 **1 Creating Include Directory:**
   Since the required include directory was missing, I manually created an "include" folder within my .local directory. This would serve as the location for including the necessary files.

   **2 Copying csq Project:**
    Next, I copied the csq repository project into the newly created "include" folder. This step is essential as it provides the required files and headers that were previously missing.

   **3 Successful Compilation:**
    After performing these steps, I attempted to compile my code once again. This time, the compilation was successful without encountering any errors.

**Pull request closed without merging**
